# Site settings
title: Tomas Dvorak
subtitle: programming, travel, sport
email: todvora@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Developer (Java, Node.js, MongoDB, security), who loves travelling and sports (ski, bike, via ferrata). Also vegan and passionate reader. Currently living in Austria and enjoying the mountains.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.tomas-dvorak.cz" # the base hostname & protocol for your site

timezone: Europe/Vienna
future: true

twitter_username: tdvorak
github_username:  todvora



# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Outputting
paginate: 10
permalink: "/posts/:title/"

sass:
    style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-coffeescript

exclude:
  - [vendor]
  - scripts
  - Gemfile
  - Gemfile.lock
  - import.rb
  - jekyll.thor
  - README.md
  - deploy_key.enc
